CREATE SCHEMA [Core];
GO

CREATE TABLE [Core].[Accounts]
(
	[AccountID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Username] VARCHAR(100) NOT NULL,
	[DisplayName] VARCHAR(500) NOT NULL,
	[Email] VARCHAR(255) NULL,
	[ProfilePictureUrl] VARCHAR(1000) NULL,
	[LastLogin] DATETIMEOFFSET NULL,
	[IsActive] BIT NOT NULL DEFAULT 1,
	[CreateDate] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	[LastModified] DATETIMEOFFSET
)
