CREATE TABLE [Core].[Seasons]
(
	[SeasonID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Year] INT NOT NULL,
	[SportID] INT NOT NULL,
	[IsCurrent] BIT NOT NULL DEFAULT 0,
	[CreateDate] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	[LastModified] DATETIMEOFFSET,

	CONSTRAINT [FK_Sports_Seasons] FOREIGN KEY ([SportID]) REFERENCES [Core].[Sports]([SportID])
)
