CREATE TABLE [dbo].[Core.Sports]
(
  [SportID] INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
	[SportName] VARCHAR(100) NOT NULL,
	[Abbreviation] VARCHAR(10) NOT NULL,	
	[CreateDate] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3),
	[LastModified] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3)
)
