CREATE TABLE [Core].[Teams]
(
	[TeamID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(100) NOT NULL,
	[City] NVARCHAR(100) NOT NULL,
	[Abbreviation] NVARCHAR(10) NOT NULL,
	[SportID] INT NOT NULL,
	[PrimaryColor] NVARCHAR(7) NOT NULL,
	[SecondaryColor] NVARCHAR(7) NULL,
	[Logo] NVARCHAR(255) NULL, -- TODO: Make this NOT NULL

	[CreateDate] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	[LastModified] DATETIMEOFFSET,

	CONSTRAINT [FK_Teams_Sports] FOREIGN KEY ([SportID]) REFERENCES [Core].[Sports]([SportID])
)
