CREATE TABLE [Core].[Sports]
(
	[SportID] INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
	[SportName] VARCHAR(100) NOT NULL,
	[League] VARCHAR(100) NOT NULL,
	[LeagueLogo] VARCHAR(1000) NULL,
	[CreateDate] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	[LastModified] DATETIMEOFFSET
)
