CREATE TABLE [dbo].[Core.Users]
(
  [UserID] INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
	[Username] VARCHAR(100) NOT NULL,
	[FirstName] VARCHAR(100) NOT NULL,
	[LastName] VARCHAR(100) NOT NULL,
	[Email] VARCHAR(255) NULL,
	[DateOfBirth] DATE NULL,
	[ProfilePictureUrl] VARCHAR(1000) NULL,
	[LastLogin] DATETIMEOFFSET NULL,
	[IsActive] BIT NOT NULL DEFAULT 1,
	[CreateDate] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3),
	[LastModified] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3)
)
