CREATE TABLE [dbo].[Core.TransactionTypes]
(
	[TransactionTypeID] INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
	[Name] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(500) NULL,
	[CreateDate] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3),
	[LastModified] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3)
)
