CREATE TABLE [dbo].[Franchise.Franchises]
(
	[FranchiseID] INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
	[LeagueID] INT NOT NULL,
	[OwnerID] INT NOT NULL,
	[Name] VARCHAR(500) NOT NULL,
	[SportID] INT NOT NULL,
	[CreateDate] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3),
	[LastModified] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3)

	FOREIGN KEY (LeagueID) REFERENCES [dbo].[League.Leagues](LeagueID),
	FOREIGN KEY (OwnerID) REFERENCES [dbo].[Core.Users](UserID),
	FOREIGN KEY (SportID) REFERENCES [dbo].[Core.Sports](SportID)
)
