CREATE TABLE [dbo].[Ranking.Rankings]
(
  [RankingID] INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
	[PlayerID]	INT NOT NULL,
	[Points] INT NOT NULL,
	[CreateDate] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3),
	[LastModified] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3),	

	FOREIGN KEY (PlayerID) REFERENCES [dbo].[Core.Players](PlayerID)
)
