CREATE TABLE [dbo].[League.LeagueUsers]
(
  [LeagueUserID] INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
	[LeagueID] INT NOT NULL,
	[UserID] INT NOT NULL,
	[JoinDate] DATETIMEOFFSET NOT NULL,
	[LeaveDate] DATETIMEOFFSET NULL,
	[CreateDate] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3),
	[LastModified] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3),

	FOREIGN KEY (LeagueID) REFERENCES [dbo].[League.Leagues](LeagueID),
	FOREIGN KEY (UserID) REFERENCES [dbo].[Core.Users](UserID)
)
