CREATE TABLE [dbo].[League.LeagueSeasons]
(
	[LeagueSeasonID] INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
	[LeagueID] INT NOT NULL,
	[Year] INT NOT NULL,
	[CreateDate] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3),
	[LastModified] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3),

	FOREIGN KEY (LeagueID) REFERENCES [dbo].[League.Leagues](LeagueID)
)