CREATE TABLE [dbo].[League.SeasonSports]
(
	[LeagueSportID] INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
	[LeagueSeasonID] INT NOT NULL,
	[SportID] INT NOT NULL,
	[CreateDate] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3),
	[LastModified] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3),

	FOREIGN KEY (LeagueSeasonID) REFERENCES [dbo].[League.LeagueSeasons](LeagueSeasonID),
	FOREIGN KEY (SportID) REFERENCES [dbo].[Core.Sports](SportID)
)
	