CREATE TABLE [dbo].[League.Leagues]
(
  [LeagueID] INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
  [LeagueName] VARCHAR(100) NOT NULL,
  [SportID] INT NOT NULL,
  [OwnerID] INT NOT NULL,
  [LogoUrl] VARCHAR(1000) NULL,
  [CreateDate] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3),
  [LastModified] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3),

	FOREIGN KEY (SportID) REFERENCES [dbo].[Core.Sports](SportID),
	FOREIGN KEY (OwnerID) REFERENCES [dbo].[Core.Users](UserID)
)
