CREATE TABLE [dbo].[Player.Players]
(
	[PlayerID] INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
	[FirstName] NVARCHAR(100) NOT NULL,
	[LastName] NVARCHAR(100) NOT NULL,
	[SportID] INT NOT NULL,

	[ExteralPlayerID] VARCHAR(100) NOT NULL,

	[CreateDate] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3),
	[LastModified] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3),
	
	FOREIGN KEY (SportID) REFERENCES [dbo].[Core.Sports](SportID)
)