
CREATE TABLE PlayerPositions (
	[PlayerPositionID] INT PRIMARY KEY IDENTITY(1,1) ,
	[PlayerID] INT NOT NULL,
	[PositionName] NVARCHAR(50) NOT NULL,
	
	[CreateDate] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3),
	[LastModified] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3),

	FOREIGN KEY (PlayerID) REFERENCES [Player.Players](PlayerID)
);
