CREATE TABLE [dbo].[Player.PlayerStatus]
(
	[PlayerStatusID] INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
	[Name] NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(500) NULL,
	[IsILEligible] BIT NOT NULL,	
	[CreateDate] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3),
	[LastModified] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3),
)
