
CREATE TABLE [dbo].[Player.PlayerStatusHistory]
(
	[PlayerStatusHistoryID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[PlayerID] INT NOT NULL,
	[PlayerStatusID] INT NOT NULL,
	[StartDate] DATETIME NOT NULL,
	[EndDate] DATETIME NULL,
	[Notes] NVARCHAR(500) NULL,
	[CreateDate] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3),
	[LastModified] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(3),

	FOREIGN KEY (PlayerID) REFERENCES [dbo].[Player.Players](PlayerID),
	FOREIGN KEY (PlayerStatusID) REFERENCES [dbo].[Player.PlayerStatus](PlayerStatusID)
);
